name: release-build

on:
  release:
    types: [created] 

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Install graalvm
      uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '20.0.0.java11'
    - name: Install native-image
      run: gu install native-image
    - name: Set version
      working-directory: ./starfish
      run: mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}" 
    - name: Build native executable
      working-directory: ./starfish
      run: mvnw package -Dnative 
    - name: Upload native executable
      id: upload-native-executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./starfish/target/starfish-${{ github.event.release.tag_name }}-runner 
        asset_name: starfish-${{ github.event.release.tag_name }}-linux
        asset_content_type: application/octet-stream
