name: release-build-native-win64

on:
  release:
    types: [created] 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: cli

jobs:
# Trigger this job only on release
  build-on-release:
    if: github.event_name=='release'&& github.event_name != 'pull_request'&& github.event_name != 'push'
    name: Build on Release
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install graalvm
      uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '20.0.0.java11'
    - name: Install native-image
      run: |
        %JAVA_HOME%/bin/gu.cmd install native-image
      shell: cmd
    - name: Configure Pagefile
      # Increased the page-file size due to memory-consumption of native-image command
      # For details see https://github.com/actions/virtual-environments/issues/785
      uses: al-cheb/configure-pagefile-action@v1.2
    - name: Set version
      run: mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}"
      shell: cmd
    - name: Build native executable
      # Invoke the native-image build with the necessary Visual Studio tooling/environment intialized
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        mvnw package -Dnative"
      shell: cmd
    - name: Upload native executable
      id: upload-native-executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/starfish-${{ github.event.release.tag_name }}.zip
        asset_name: starfish-win64.zip
        asset_content_type: application/octet-stream

# Trigger this job only on Push or Pull-Request
  build-on-push-pr:
    if: github.event_name!='release'&&( github.event_name == 'pull_request'|| github.event_name == 'push')
    name: Build on Push or PR
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.0.0.java11'
      - name: Install native-image
        run: |
          %JAVA_HOME%/bin/gu.cmd install native-image
        shell: cmd
      - name: Configure Pagefile
        # Increased the page-file size due to memory-consumption of native-image command
        # For details see https://github.com/actions/virtual-environments/issues/785
        uses: al-cheb/configure-pagefile-action@v1.2
      - name: Set version
        run: ./mvnw versions:set -DnewVersion="${{github.sha}}" 
        shell: cmd
      - name: Build native executable
        # Invoke the native-image build with the necessary Visual Studio tooling/environment intialized
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
          mvnw package -Dnative"
        shell: cmd
      - name: Upload native executable
        id: upload-native-executable
        uses: actions/upload-artifact@v2
        with:
          name: starfish-win64-${{github.sha}}.zip
          path: ./target/starfish-${{github.sha}}.zip
